#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout (binding = 0) uniform UniformBufferObject {
    mat4 viewProjection;
    vec4 spheres[20]; // {vec3(center), radius}
    vec4 camPos;
    int sphereCount;
} ubo;

// One float per voxel
layout(r32f, binding = 1) uniform image3D fieldTex;

void main() {
    ivec3 id = ivec3(gl_GlobalInvocationID);
    ivec3 dim = imageSize(fieldTex);
    if (any(greaterThanEqual(id, dim - 1))) return;

    // [-1,1) -> [-dim/2, dim/2)
    vec3 p = vec3(id) - vec3(dim / 2); 

    float f = 0.0;

    // Field = sum of multiple spheres (using 1/r falloff)
    for (int i = 0; i < ubo.sphereCount; i++)
    {
        float r = length(p - ubo.spheres[i].xyz);
        r = max(r, 1e-10); 
        float fp = ubo.spheres[i].w / r;
        f += fp;
    }
    
    imageStore(fieldTex, id, vec4(f, 0, 0, 0));
}

